"""empty message

Revision ID: 0cdd55c528ae
Revises: 41e1d9dae23f
Create Date: 2023-05-06 23:09:52.103372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cdd55c528ae'
down_revision = '41e1d9dae23f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
