"""empty message

Revision ID: 396ee0ad50c2
Revises: 6489c194e23a
Create Date: 2023-05-07 00:30:05.387945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396ee0ad50c2'
down_revision = '6489c194e23a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('algo_course', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'algo_course', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'algo_course', type_='foreignkey')
    op.drop_column('algo_course', 'course_id')
    op.drop_table('course')
    # ### end Alembic commands ###
