"""empty message

Revision ID: 39aaead3ce91
Revises: da8fb5aa1247
Create Date: 2023-04-16 20:05:58.922184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39aaead3ce91'
down_revision = 'da8fb5aa1247'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
