"""Change Datetime to Date in task table

Revision ID: 5ca68f725d07
Revises: 0f1c021d21c7
Create Date: 2023-04-09 21:05:40.893341

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5ca68f725d07'
down_revision = '0f1c021d21c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
