"""Add start_date column in done_task table;

Revision ID: 7412378df8b9
Revises: c9dd1c2fd839
Create Date: 2023-04-14 23:53:51.798192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7412378df8b9'
down_revision = 'c9dd1c2fd839'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('done_task', sa.Column('start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('done_task', 'start_date')
    # ### end Alembic commands ###
