"""Change Datetime to Date in task table

Revision ID: 83f9a1bce4e5
Revises: ff59c13d4c19
Create Date: 2023-04-09 21:12:32.455209

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '83f9a1bce4e5'
down_revision = 'ff59c13d4c19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('start_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'start_date')
    # ### end Alembic commands ###
