"""empty message

Revision ID: cd3aee97624c
Revises: 53acab953193
Create Date: 2023-04-26 01:41:46.536860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd3aee97624c'
down_revision = '53acab953193'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_category', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'note_category', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note_category', type_='foreignkey')
    op.drop_column('note_category', 'user_id')
    # ### end Alembic commands ###
