"""empty message

Revision ID: d8a77f322c47
Revises: 396ee0ad50c2
Create Date: 2023-05-07 16:39:44.229457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a77f322c47'
down_revision = '396ee0ad50c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
