"""Delete task_id from done_task

Revision ID: efe604cce127
Revises: 7412378df8b9
Create Date: 2023-04-14 23:54:42.025625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe604cce127'
down_revision = '7412378df8b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('done_task', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('done_task', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
